### PR TITLE
[issue-162] Update and fix browser update setup

### LINKED ISSUE #162: Remove IE from supported browsers
Currently the browser update feature requires IE 8 or higher but actually we should drop IE support altogether because its outdated and barely used anymore.

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixes #162 by upgrading the `browser-update` package and improves the browser detection to work with negative offsets, so we don't have to maintain the latest browser versions ourself.

### CODE REVIEW

File: source/features/outdated-browser/BrowserUpdate.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export const BrowserUpdate = () => {
         reminderClosed: 150,
         // if the user explicitly closes message it reappears after x hours
 
-        required: { i: 8, f: 25, o: 17, s: 9, c: 22 },
+        required: { e: -3, f: -3, o: -3, s: -1, c: -3 },
```
Comment (rhyslbw) [inline source/features/outdated-browser/BrowserUpdate.tsx]: :sunglasses:
